name: PleasantChats
version: 1.1

main: ru.mishaneyt.chats.Main
authors: [ PleasantVKChannel ]
softdepend:
  - PlaceholderAPI

commands:
  pleasantchats:
    default: op
    aliases: [ pc ]

  donatechat:
    default: default
    aliases: [ dc ]

  adminchat:
    default: default
    aliases: [ ac ]

  msg:
    default: default
    aliases: [ m ]